In [1]:
import numpy as np
from Minesweeper import Minesweeper

ROWS, COLS = 10, 10
MINES = 20
env = Minesweeper((ROWS, COLS), MINES)

In [46]:
def get_slice(board, i, j):
    min_x = max(0, i-1)
    max_x = min(env.rows-1, i+1)
    min_y = max(0, j-1)
    max_y = min(env.cols-1, j+1)
    
    return board[min_x:max_x+1, min_y:max_y+1]

np.where(env.solved_board == env.solved_board[env.get_slice(2,2)])

C:\Users\Rednaxela\AppData\Local\Temp\ipykernel_11740\3374367764.py:9: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  np.where(env.solved_board == env.solved_board[env.get_slice(2,2)])


(array([], dtype=int64),)

In [43]:
def get_slice(self, i, j):
    min_x = max(0, i-1)
    max_x = min(self.rows-1, i+1)
    min_y = max(0, j-1)
    max_y = min(self.cols-1, j+1)
    
    return np.s_[min_x:max_x+1, min_y:max_y+1]


print("first:\n", env.solved_board)
print("second:\n", env.solved_board[env.get_slice(2,2)])

first:
 [[ 0  0  0  1  1  2 -1 -1  3  1]
 [ 1  1  0  1 -1  3  5 -1  4 -1]
 [-1  1  1  2  2  2 -1 -1  3  1]
 [ 2  3  3 -1  1  1  2  2  1  0]
 [ 1 -1 -1  2  1  0  0  1  1  1]
 [ 1  2  2  1  1  1  1  1 -1  1]
 [ 1  1  2  2  3 -1  1  1  1  1]
 [ 1 -1  4 -1 -1  3  2  1  0  0]
 [ 2  3 -1 -1  3  2 -1  1  0  0]
 [ 1 -1  3  2  1  1  1  1  0  0]]
second:
 [[ 1  0  1]
 [ 1  1  2]
 [ 3  3 -1]]


In [11]:
def check_saturation(x, y):
    env.solved

env.step(12)
env.render()

   ░  ░  ░  1  1  █ -1  █  █  █ 
   1  1  ░  1  █  █  █  █  █  █ 
   █  1  1  2  █  █  █  █  █  █ 
   2  █  █  █  1  █  █  █  1  █ 
   █  █  █  █  █  █  █  █  █  █ 
   █  █  █  █  █  █  █  █  █  █ 
   █  █  █  █  █  █  █  █  █  █ 
   █  █  █  █  █  █  █  █  █  █ 
   █  █  █  █  █  █  █  █  █  █ 
   █  █  █  █  █  █  █  █  █  █  
