In [2]:
import numpy as np

In [1]:
from M_simple import *
ROWS = 3
COLS = 3
MINES = 1

In [17]:
def layer_board(board, solved_board):
    rows, cols = solved_board.shape
    for i in range(rows):
        for j in range(cols):
            if solved_board[i,j] != -1:
                board[solved_board[i,j]][i,j] = 1
    return board

np.random.seed(9999)

board, mine_board = create_board(ROWS, COLS, MINES)
solved_board = solve_board(mine_board)

layer_board(board, solved_board)
board

array([[[1, 0, 0],
        [1, 0, 0],
        [1, 1, 1]],

       [[0, 1, 0],
        [0, 1, 1],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [60]:
ting = lambda W, H, K, S, P: ((W - K + 2*P)/S, (H - K + 2*P)/S)

ting(10, 10, 5, 1, 2)

(9.0, 9.0)

In [43]:
ROWS = 10
COLS = 10
MINES = 20
CLOSED = 9

mine_board = np.zeros(ROWS*COLS, dtype=int)
mine_board[np.random.choice(ROWS*COLS, MINES, replace=False)] = 1
mine_board = mine_board.reshape(ROWS, COLS)

print_board = lambda arr: print(np.array2string(arr, separator="  ").replace('0', '░').replace('1', '█').replace("[", " ").replace("]", " "))
print_board(mine_board)

  █  ░  ░  ░  █  ░  █  █  ░  ░ 
  █  █  ░  ░  █  ░  ░  ░  ░  █ 
  ░  ░  ░  ░  █  ░  ░  █  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  █ 
  ░  ░  ░  ░  █  ░  ░  ░  ░  ░ 
  ░  ░  █  ░  ░  ░  █  ░  ░  ░ 
  ░  ░  ░  █  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  █  ░  ░  ░  ░  ░  ░ 
  █  ░  █  ░  █  ░  ░  ░  █  ░  


In [46]:
def create_board():
    board = np.zeros((10, ROWS, COLS), dtype=int)
    board[CLOSED] = True

    mine_board = np.zeros(ROWS*COLS, dtype=int)
    mine_board[np.random.choice(ROWS*COLS, MINES, replace=False)] = 1
    mine_board = mine_board.reshape(ROWS, COLS)
    
    return board, mine_board

# check for mines in the neighbours
def count_neighbour_mines(mine_board, x, y):

    min_x = max(0, x-1)
    max_x = min(ROWS-1, x+1)
    min_y = max(0, y-1)
    max_y = min(COLS-1, y+1)
    mines = mine_board[min_x:max_x+1, min_y:max_y+1]
    return np.sum(mines)
                    

# open the neighbours
def open_neighbour_cells(board, mine_board, x, y):
    board[CLOSED, x, y] = False

    mines = count_neighbour_mines(mine_board, x, y)
    board[mines, x, y] = True

    return board

In [6]:
from M_simple import Minesweeper

env = Minesweeper((10, 10), 20, [200,-100,5])

env.solved_board, env.mine_board

(array([[ 2,  2,  1,  1, -1,  1,  0,  1,  1,  1],
        [-1, -1,  1,  1,  1,  2,  1,  2, -1,  1],
        [ 2,  3,  2,  1,  0,  1, -1,  2,  1,  1],
        [ 0,  2, -1,  2,  0,  2,  2,  2,  1,  1],
        [ 0,  3, -1,  4,  1,  2, -1,  3,  2, -1],
        [ 0,  2, -1, -1,  2,  3, -1, -1,  3,  2],
        [ 1,  2,  2,  2,  2, -1,  3,  3, -1,  1],
        [-1,  2,  2,  1,  2,  2,  2,  2,  1,  1],
        [ 2, -1,  3, -1,  1,  1, -1,  1,  0,  0],
        [ 1,  2, -1,  2,  1,  1,  1,  1,  0,  0]]),
 array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [1, 1, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 1, 0, 0, 1],
        [0, 0, 1, 1, 0, 0, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 1, 0, 0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]]))

In [60]:
[print_board(i)+" " for i in create_board()[0]]

  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░  
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░  
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░  
  ░  ░  ░  ░  ░  ░  ░  ░  ░  ░ 
  ░  

[None, None, None, None, None, None, None, None, None, None]

In [3]:


def reset_board():
    board = np.zeros((10, ROWS, COLS), dtype=bool)
    mine_board = np.zeros((ROWS, COLS), dtype=bool)
    board[CLOSED] = 1

    for i in np.random.choice(ROWS*COLS, ROWS*COLS, replace=False)[:MINES]:
        mine_board[i//ROWS, i%COLS] = 1
        
    return board, mine_board
    # return board, mine_board

In [45]:
def method1():
    mine_board = np.zeros((ROWS,COLS), dtype=int)

    for i in np.random.choice(ROWS*COLS, ROWS*COLS, replace=False)[:MINES]:
        mine_board[i//ROWS, i%COLS] = 1


In [6]:
import numpy as np

def create_board(rows, cols, mines):
    board = np.zeros((10, rows, cols), dtype=int)
    board[-1] = 1
    
    mine_board = np.zeros(rows*cols, dtype=int) #<-- flat
    mine_board[np.random.choice(rows*cols, mines, replace=False)] = 1
    mine_board = mine_board.reshape(rows, cols) #<-- grid
    return board, mine_board


def solve_board(board):
    _, rows, cols = board.shape
    solved_board = board.copy()
    for i,j in np.argwhere(solved_board == -1):
        for k in range(-1, 2):
            for l in range(-1, 2):
                if i + k >= 0 and i + k < cols and j + l >= 0 and j + l < rows:
                    if solved_board[i + k][j + l] != -1:
                        solved_board[i + k][j + l] += 1
    return solved_board

In [59]:
mine_board = create_board(10,10,20)[1]

In [140]:
for k in range(-1, 2):
    for l in range(-1, 2):
        if i + k >= 0 and i + k < self.cols and j + l >= 0 and j + l < self.rows:
            if solved_board[i + k][j + l] != -1:
                solved_board[i + k][j + l] += 1

array([[  1,   1,   1,   1,   1,   1,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1,   1,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1,   1,   1,   1,   1,   1],
       [  1,   1,   1,   1,  -9,  -9,  -9,   1,   1,   1],
       [  0,   0,   1,   0, -10, -10, -10,   0,   0,   0],
       [  1,   0,   0,   0,  -9, -10, -10,   0,   0,   0],
       [  0,   0,   0,   0,   1,   1,   1,   0,   0,   0],
       [  0,   0,   1,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   1,   0,   0,   0,   0,   0],
       [  1,   0,   0,   0,   0,   0,   1,   0,   0,   0]])

In [153]:
mine_board = 
mine_board

array([[ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8],
       [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8],
       [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8],
       [ 8,  8,  8,  8, -1, -1, -1,  8,  8,  8],
       [ 0,  0,  8,  0, -1, -1, -1,  0,  0,  0],
       [ 8,  0,  0,  0, -1, -1, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  8,  8,  8,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  8,  0,  0,  0,  0,  0],
       [ 8,  0,  0,  0,  0,  0,  8,  0,  0,  0]])

In [145]:
def get_slice(board, x, y):
    min_x = max(0, x-1)
    max_x = min(board.shape[0]-1, x+1)
    min_y = max(0, y-1)
    max_y = min(board.shape[1]-1, y+1)

    return np.s_[min_x:max_x+1, min_y:max_y+1]

mine_board[get_slice(mine_board, 4,4)]

array([[  1,  -9,  -9],
       [  0, -10, -10],
       [  0,  -9, -10]])

In [ ]:
def solve_board(self, mine_board):
    solved_board = mine_board.copy()
    for i,j in np.argwhere(solved_board == -1):
        for k in range(-1, 2):
            for l in range(-1, 2):
                if i + k >= 0 and i + k < self.cols and j + l >= 0 and j + l < self.rows:
                    if solved_board[i + k][j + l] != -1:
                        solved_board[i + k][j + l] += 1
    return solved_board

In [ ]:

mine_board[x,y] = 0
mine_board[min_pos] = 1
solved_board[min_pos]

In [131]:
def move_mine(mine_board, solved_board, x, y):
    new_pos = np.argmin(mine_board) // 10, np.argmin(mine_board) % 10
    mine_board[x,y] = 0
    mine_board[new_pos] = 1
    
    min_x = max(0, x-1)
    max_x = min(solved_board.shape[0]-1, x+1)
    min_y = max(0, y-1)
    max_y = min(solved_board.shape[1]-1, y+1)

    solved_board[x,y] += 1
    solved_board[min_x:max_x+1, min_y:max_y+1] -= 1
    return solved_board

In [137]:
mine_board
add_one(mine_board, 4,5)

array([[  1,   1,   1,   1,   1,   1,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1,   1,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1,   1,   1,   1,   1,   1],
       [  1,   1,   1,   1,  -9,  -9,  -9,   1,   1,   1],
       [  0,   0,   1,   0, -10, -10, -10,   0,   0,   0],
       [  1,   0,   0,   0,  -9, -10, -10,   0,   0,   0],
       [  0,   0,   0,   0,   1,   1,   1,   0,   0,   0],
       [  0,   0,   1,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   1,   0,   0,   0,   0,   0],
       [  1,   0,   0,   0,   0,   0,   1,   0,   0,   0]])

In [ ]:


def solve_board(self, mine_board):
    rows, cols = mine_board.shape
    solved_board = mine_board.copy()
    for i,j in np.argwhere(solved_board == -1):
        for k in range(-1, 2):
            for l in range(-1, 2):
                if i + k >= 0 and i + k < cols and j + l >= 0 and j + l < rows:
                    if solved_board[i + k][j + l] != -1:
                        solved_board[i + k][j + l] += 1
    return solved_board

In [98]:
min_coord = (np.argmin(mine_board) // 10, np.argmin(mine_board) % 10)
mine_board[min_coord] = 1
mine_board

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 0]])

In [16]:
mine_board[np.argmin(mine_board[0]),0] = 1
mine_board

array([[1, 0, 0, 1, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 1, 0, 0, 0, 0, 1, 0, 0]])

In [9]:
ROWS = 10
COLS = 10
MINES = 20
CLOSED = 9

def place_mines(mine_board):
    
    # generate mines number of random unique numbers between 0 and 99
    mines = np.random.choice(ROWS*COLS, MINES, replace=False)
    
    for mine in mines:
        x = mine // ROWS
        y = mine % COLS
        mine_board[x, y] = 1

    return mine_board


# make last layer all closed
def reset_board():

    board = np.zeros((10, ROWS, COLS), dtype=int)
    mine_board = np.zeros((ROWS, COLS), dtype=int)
    board[CLOSED] = 1

    mine_board = place_mines(mine_board)
    
    return board, mine_board


# check for mines in the neighbours
def count_neighbour_mines(mine_board, x, y):

    min_x = max(0, x-1)
    max_x = min(ROWS-1, x+1)
    min_y = max(0, y-1)
    max_y = min(COLS-1, y+1)
    mines = mine_board[min_x:max_x+1, min_y:max_y+1]
    return np.sum(mines)
                    

# open the neighbours
def open_neighbour_cells(board, mine_board, x, y):
    board[CLOSED, x, y] = 0

    mines = count_neighbour_mines(mine_board, x, y)
    board[mines, x, y] = 1

    return board


def step(board, action):
    x = action // ROWS
    y = action % COLS
    
    if mine_board[x, y]:
        reward = -100
        done = True
    else:
        board = open_neighbour_cells(board, mine_board, x, y)
        reward = 20
        done = False
    if np.sum(board[CLOSED]) == MINES:
        reward = 100
        done = True

    return board, reward, done

In [30]:
np.random.seed(9999)
print_board = lambda arr: print(np.array2string(arr, separator="  ").replace('0', '░').replace('1', '█').replace("[", " ").replace("]", " "))

print_board(reset_board()[1])
print()
print_board(create_board(10,10,20)[1])

  ░  █  ░  ░  ░  █  ░  █  ░  ░ 
  ░  ░  ░  █  ░  █  ░  ░  ░  ░ 
  ░  ░  ░  █  ░  ░  ░  ░  ░  ░ 
  ░  █  ░  ░  █  █  ░  ░  ░  ░ 
  ░  ░  ░  ░  █  ░  ░  ░  ░  █ 
  █  ░  ░  ░  ░  █  ░  █  ░  ░ 
  ░  ░  ░  ░  ░  █  ░  ░  ░  ░ 
  ░  ░  ░  █  █  ░  ░  ░  ░  ░ 
  ░  ░  ░  █  ░  ░  ░  ░  ░  █ 
  ░  ░  ░  █  ░  ░  ░  ░  ░  ░  

  ░  █  ░  █  ░  █  ░  ░  ░  ░ 
  ░  █  ░  ░  ░  ░  ░  ░  █  █ 
  ░  ░  █  ░  ░  ░  ░  █  ░  ░ 
  ░  ░  ░  ░  ░  ░  ░  █  ░  ░ 
  ░  ░  ░  █  ░  ░  ░  ░  ░  ░ 
  ░  ░  █  █  ░  ░  ░  ░  ░  █ 
  █  ░  ░  ░  ░  ░  ░  ░  █  █ 
  ░  ░  █  ░  ░  ░  ░  ░  ░  ░ 
  ░  ░  ░  ░  █  █  ░  ░  ░  ░ 
  █  ░  ░  ░  ░  ░  ░  ░  ░  ░  


In [166]:
def method3():
    invalid_actions = mine_board.flatten().nonzero()[0]
    valid_actions = (mine_board.flatten() == False).nonzero()[0]

    invalid_actions
    valid_actions

In [181]:
def reset_board():

    board = np.zeros((10, ROWS, COLS), dtype=bool)
    mine_board = np.zeros((ROWS, COLS), dtype=bool)
    board[CLOSED] = True

    mines = np.random.choice(ROWS*COLS, MINES, replace=False)
    
    for mine in mines:
        x = mine // ROWS
        y = mine % COLS
        mine_board[x, y] = True
    
    return board, mine_board

In [2]:
import numpy as np

np.zeros((10,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [189]:
import torch
import numpy as np

In [167]:
def method4():
    invalid_actions = mine_board.flatten().nonzero()[0]
    valid_actions = np.logical_not(mine_board.flatten()).nonzero()[0]

    invalid_actions
    valid_actions

In [44]:
print_board = lambda arr: print(np.array2string(arr, separator="  ").replace('0', '░').replace('1', '█').replace("[", " ").replace("]", " "))

def method2():
    mines = np.random.choice(ROWS*COLS, MINES, replace=False)
    mine_board = np.zeros((ROWS,COLS), dtype=int)

    for mine in mines:
        x = mine // ROWS
        y = mine % COLS
        mine_board[x, y] = 1

# print_board(mine_board)

In [173]:
for _ in range(500_000):
    method3()

In [172]:
for _ in range(500_000):
    method4()